// conexion a la base de jgv
module.exports = [{
        empresa: 0 // debe ir vacia
    },
    {
        empresa: 1, // varsovienne
        razon_social_empresa: 'BOMBONES VARSOVIENNE S.A.',
        nombre_encargado_rrhh: 'Victoria Brunel Guerrero',
        cargo_encargado_rrhh: 'Encargada de Recursos Humanos',
        direccion_empresa_1: 'Av. Einstein 787, Recoleta',
        direccion_empresa_2: 'Santiago, Chile',
        telefonos_empresa: 'Tel. +56 2 26210960',
        sitio_web_empresa: 'www.varsovienne.cl',
        imagen_cert_antig: 'https://kinetik.cl/rrhh01/img/varso_logo.png',
        firma_cert_antig: 'https://kinetik.cl/rrhh01/img/varso_firma.png',
        anticipos: 'arivas@gyanet.cl',
        anticipos_cc: 'jogv66@gmail.com',
        vacaciones: 'arivas@gyanet.cl',
        vacaciones_cc: 'jogv66@gmail.com',
        licencias: 'arivas@gyanet.cl',
        licencias_cc: 'jogv66@gmail.com',
        certificados: 'arivas@gyanet.cl',
        certificados_cc: 'jogv66@gmail.com',
        cambios: 'arivas@gyanet.cl',
        cambios_cc: 'jogv66@gmail.com',
    },
    {
        empresa: 2, // REDHAT
        razon_social_empresa: 'RED HAT CHILE LTDA.',
        nombre_encargado_rrhh: 'nombre_del_encagado',
        cargo_encargado_rrhh: 'Encargado de Recursos Humanos',
        direccion_empresa_1: 'Av. Nueva Tajamar 481 oficina 908 Torre Norte',
        direccion_empresa_2: 'Santiago, Chile',
        telefonos_empresa: 'Tel. +562 23651683 - +562 25977000',
        sitio_web_empresa: 'www.redhat.com/es',
        imagen_cert_antig: 'https://kinetik.cl/rrhh01/img/redhat_logo.png',
        firma_cert_antig: 'https://kinetik.cl/rrhh01/img/redhat_firma.png',
        anticipos: 'arivas@gyanet.cl',
        anticipos_cc: 'jogv66@gmail.com',
        vacaciones: 'arivas@gyanet.cl',
        vacaciones_cc: 'jogv66@gmail.com',
        licencias: 'arivas@gyanet.cl',
        licencias_cc: 'jogv66@gmail.com',
        certificados: 'arivas@gyanet.cl',
        certificados_cc: 'jogv66@gmail.com',
        cambios: 'arivas@gyanet.cl',
        cambios_cc: 'jogv66@gmail.com',
    },
    {
        empresa: 3, // SUNSWETT
        razon_social_empresa: 'SUNSWEET CHILE S.A.',
        nombre_encargado_rrhh: 'nombre_del_encagado',
        cargo_encargado_rrhh: 'Encargado de Recursos Humanos',
        direccion_empresa_1: 'Av. Nueva Tajamar 481, Of- 908, Torre Norte',
        direccion_empresa_2: 'Santiago, Chile',
        telefonos_empresa: 'Tel. 442350180',
        sitio_web_empresa: '',
        imagen_cert_antig: 'https://kinetik.cl/rrhh01/img/sunswett_logo.png',
        firma_cert_antig: 'https://kinetik.cl/rrhh01/img/sunswett_firma.png',
        anticipos: 'arivas@gyanet.cl',
        anticipos_cc: 'jogv66@gmail.com',
        vacaciones: 'arivas@gyanet.cl',
        vacaciones_cc: 'jogv66@gmail.com',
        licencias: 'arivas@gyanet.cl',
        licencias_cc: 'jogv66@gmail.com',
        certificados: 'arivas@gyanet.cl',
        certificados_cc: 'jogv66@gmail.com',
        cambios: 'arivas@gyanet.cl',
        cambios_cc: 'jogv66@gmail.com',
    },
];